### ISSUE TITLE
Teaching and Building WebVR building Blocks

### ISSUE THREAD

**Issue by rabimba** [mozilla/participation-leaders-accountability#12]
## Objective:

Work on VR demos using A-Frame for connected Devices tracks to gain widespread familiarity with WebVR.
## Key Goals:
- Build some basic demos with A-Frame that can be run in any mobile 
- Take session make developers and users aware of how they can do it and can benefit form it 
- Teach others to contribute in it 
## Related Issues & Links:
- "Tech Immersion" program in NYC at mid-march.
- HackBCA at NJ at 1st week of April
## Roles:

Who owns this plan: Dietrich Ayala(@autonome) & @rabimba
Who is involved: Rabimba Karanjai, MozVR , @autonome , @end3r (Building Material)
## Immediate next steps:
- [x] Take Part in "Tech Immersion" Program at Renaissance HS in Harlem, NYC(Due: Jan 28th) 
- [x] Procure Cardboard viewers for everyone (Due: Feb 27th/TBD) 
- [x] Build defined curriculum (Due: Mar 12th) 
#### A rolling Curriculum
- [x] Day 1 Activities
- [x] Day 2 Activities
- [x] Day 3 Activities
### What role(s) are you most interested in playing for this campaign?
- Building Curricula
- Teaching and hacking
- Mentoring others so that they can do it further
### Which campuses are potential participants in this campaign? Are these technical schools or liberal arts schools?
- Renaissance HS in Harlem, NYC
- Bergen County Academies
### Who are the stakeholders you need to engage?
- New York City Dept of Education
- MozVR Team
### How are you going to do that engagement?
- "Tech Immersion" is part of that effort. We already have that.
- Dietrich is working closely with MozVR team to enlist their help. Also we have interested participants from Firefox team (Jared Wein) taking part
### Where we need help?
- 360 degree Videos (Not uploaded in youtube). If you have them we can use them.
### 

== WIP ==

**Comment by flaki** [comment]
Subscribing! Good luck with that stuff!

**Comment by rabimba** [comment]
## Updates:
- [x] Curriculum Done 
- [x] VR Teaching kit Complete
- [x] Build your own VR materials

Link to materials: [Done] [WIP] Will update after event on 14-16th March
Link to Slide: @autonome is on it

**Comment by rabimba** [comment]
_**Updates**_

**Trip report**: http://blog.rabimba.com/2016/05/vr-for-everyone-when-you-get-to-play.html
**Link To Materials**: 
- https://goo.gl/rmPVMu
- https://goo.gl/A0CWOh

**Link to slide**: https://goo.gl/rmPVMu

**Code:** http://codepen.io/rabimba/

**Comment by rabimba** [comment]
_**Update 2**_

Aframe Team covered it!
**Blog**: https://blog.mozvr.com/fun-webvr-times-at-innovation-high/ 
**Update**: https://aframe.io/blog/awoa-15

**Comment by miquael** [comment]
where's the curriculum ?
