### ISSUE TITLE
Build Out Awesome Resource For Running Personal Leardership and Public Speaking Training

### ISSUE THREAD

**Issue by gauthraj** [mozilla/participation-leaders-accountability#14]
## Objective:

Take the learning and insights from "Personal Leadership" & "Public Speaking" session at Leadership Summit and create set of resources  to run the two trainings at the regional communities.  
## Key Results:
- 2 trainings using this resources
- Atleast 10 people find the trainings useful
- Atleast 5 people felt empowered that they go out and talk in an event confidently 
## Related Issues & Links:

[My Reflections on Leadership Summit](http://mozraj.blogspot.in/2016/01/my-reflections-on-mozilla-leadership.html)
## Roles:

Who owns this plan: @gauthraj
Who is involved: (If interested, you're welcome to help)
## Immediate next steps:
- [ ] Write a detailed blogpost about the idea, goals and share in public
- [ ] Have a kick-off call with those who are interested. Create a Wiki for the project
- [ ] Populate useful resources and add it to the wiki. Step by Step Guidelines to run successful trainings
- [ ] Test the Model and ask for feedback

**Comment by fayepal** [comment]
Hey Raj! I am interested to help! This could also improve the public speaking training material we have for FSA right now.
