### ISSUE TITLE
Organize a Campus campaign in Maracaibo, Venezuela

### ISSUE THREAD

**Issue by daas88** [mozilla/participation-leaders-accountability#19]
## Objective:

Organize a Campus Campaign in a university in Maracaibo, Venezuela, focusing on raising awareness and teaching how to protect your online privacy.  
## Key Results:
- Finding a student in said campus that wants to take the lead of the campaign 
- Finding at least 3 students that also contribute with our campus leader 
- Doing at least one mentoring session with said students
## Roles:

Who owns this plan: @daas88
Who is involved: I need to find them!
## Immediate next steps:
- [ ] Contact a few students interested in participating ([medium], Due: Feb 14th) 
- [ ] Explaining them the importance of the campaign and their roles in it ([small], Due: Feb 14th) 
- [ ] Planning cool things to do in this campaign ([small], Due: Feb 29th) 
#### What role(s) are you most interested in playing for this campaign?
- Building resources:
  I'd like to make a video that could be used in other campuses.
- Recruiting and supporting campus leaders
  Since I'm starting just by myself, I need to recruit the campus leaders and contributors
#### Which campuses are potential participants in this campaign? Are these technical schools or liberal arts schools?

La Universidad del Zulia: biggest university in the state. It's public. It has serveral technical and liberal arts campuses. I'd probably choose a technical campus as the target.
Universidad Cecilio Acosta: a private university, the closest to my home. It's a liberal arts school, but events like FLISOL have taken place in there.
#### Who are the stakeholders you need to engage?

College administration
"Centro de estudiantes", a group of activist students that could help
#### How are you going to do that engagement?

Going to the campus and talking to someone in college's administration to ask for permission and for people who might be interested in participating, as well as visiting the little office given to the "centro de estudiantes", to do the same. Also asking the maintainers of the college's social accounts to post a few tweets or facebook posts. 
#### Who are the team members you need to engage?

TBC
#### How are you going to do that?

TBC
#### What are some tactics you will pursue to achieve your goals?

Using social media to reach more people (hopefully even reaching people in other states or cities).
Putting brochures in bulletin boards around the campus
Making presentations and other kinds of visual teaching resources focusing on online privacy (or translating them if there are good ones)

**Comment by ThePhoenixBird** [comment]
Reference: https://github.com/mozillavenezuela/participation/issues/1
