### ISSUE TITLE
Throw the most amazing CPJ party by April

### ISSUE THREAD

**Issue by geroter** [mozilla/participation-leaders-accountability#2]
## Objective:

Throw the most amazing CPJ party by April
## Key Results:
- 10 CPJs at the party
- [Measure of success 2 -- a good indication that you are making progress toward your objective] 
- [Measure of success 3 -- a good indication that you are making progress toward your objective] 
## Related Issues & Links:

[Reference meta issues, past issues or other people's issues if you might be working together] #
## Roles:

Who owns this plan: @geroter
Who is involved: @alexlakatos
## Immediate next steps:
- [x] First, put mittens on all of the kittens ([small, medium, large], Due: Feb 7th) 
- [ ] Second, put boots on all of the kittens ([small, medium, large], Due: Feb 7th) 
- [ ] Third, put hats on all of the kittens ([small, medium, large], Due: Feb 7th)

**Comment by soapdog** [comment]
Cc @soapdog: I want to go to the party :smile-cat:

**Comment by tripad** [comment]
Tropical weather is as not compatibility with PJs
We need CShorts party instructions

**Comment by rosanardila** [comment]
Closing this. We'll reopen with the specs for CShorts!
