### ISSUE TITLE
Phase 0 Campus Campaign in the Mexico/Odin Mojica

### ISSUE THREAD

**Issue by odinm** [mozilla/participation-leaders-accountability#22]
## Objective:

<table border="1" width="300px" align="center" cellpadding="10px">
   <table>
    <tr>
        <td>English</td>
        <td>Español</td>
    </tr>
    <tr>
        <td>
Assist the growth of the local community taking as flag the issue of privacy of information in two schools, the UNAM Faculty of Engineering with the support of various mozillians studying there, the other is the University The Cloister of Sor Juana center that does not impart educational and technical careers are conducting a seminar called "hacker ethic, safety and security", apart from addressing the issue of privacy will seek to raise awareness on net neutrality and the importance of a free Internet, and if I can help them learn to create within the web.</td>
        <td>Ayudar al crecimiento de la comunidad local tomando como bandera el tema de la privacidad de la información en dos centros educativos, la UNAM en la Facultad de Ingenieria con el apoyo de varios mozillians que estudian ahí y en la Universidad del Claustro de Sor Juana centro educativo que no imparte carreras técnicas y que esta realizando un seminario llamado: "Etica hacker, seguridad y vigilancia", aparte de tocar el tema de la privacidad buscaré hacer conciencia sobre la neutralidad en la red y la importancia de contar con un Internet libre donde no busquen violentar su naturaleza, y si me es posible ayudar a que aprendan a crear dentro de la web.</td>
    </tr>
   <td>Transmitted to the community seen in the workshops of Personal Leardership and Public Speaking Training</td>
   <td>Transmitir a la comunidad lo visto en los talleres de Personal Leardership y Public Speaking Training</td>
</table>
## Key Results:

<table border="1" width="300px" align="center" cellpadding="10px">
    <tr>
        <td>English</td>
        <td>Español</td>
    </tr>
    <tr>
        <td>- Measure of success 1 -- increase the number of members in the community of Mozilla Mexico</td>
        <td>Medición de objetivos 1 -- aumentar el número de integrantes de en la comunidad de Mozilla México.</td>
    </tr>
    <tr>
        <td>Measure of success 2 -- raise the awareness of participants attending the various meetings and talks on campuses about the importance of privacy and tell them how Mozilla is participating in the protection and help them learn to use different tools to protect your information, important to create brochures and campaigns on social networking community on the subject.</td>
        <td>Medición de objetivos 2 -- Crear conciencia en los asistentes que acudan a las diferentes reuniones y charlas en los campus sobre la importancia de la privacidad y decirles como Mozilla esta participando en esta protección, así como ayudarles a saber usar diferentes herramientas para proteger su información, importante crear folletos y campañas en las redes sociales de la comunidad sobre el tema.</td>
    </tr>
     <tr>
        <td>Measure of success 3 -- through teaching kits Mozilla help people understand what the web and how they can create and contribute content to the Web, to stop being are consumers and creators.</td>
        <td>Medición de objetivos 3 -- por medio de los kits de enseñanza de Mozilla ayudar a que la gente entiendan lo que es la web y como pueden crear contenidos y aportar a la web, dejar de ser consumidores.</td>
    </tr>
</table>

<table border="1" width="300px" align="center" cellpadding="10px">
    <tr>
        <td>English</td>
        <td>Español</td>
    </tr>
    <tr>
        <td> Measure of success 1 -- help to have a better relationship between the members of the local community.
</td>
        <td>Medición de objetivos 1-- ayudar a contar con una mejor relación entre los integrantes de la comunidad local.</td>
    </tr>
    <tr>
        <td>Measure of success 2 -- helping the community to learn to speak better in public https://wiki.mozilla.org/TechSpeakers</td>
        <td>Medición de objetivos 2 --  ayudar a la comunidad para que podamos hablar mejor en público</td>
    </tr>
</table>

## Related Issues & Links:

[Reference meta issues, past issues or other people's issues if you might be working together] #
## Roles:

Who owns this plan: 
Who is involved: 
## Immediate next steps | Pasos a seguir:
- [ ] First, put mittens on all of the kittens ([small, medium, large], Due: Feb 7th) 
- [ ] Second, put boots on all of the kittens ([small, medium, large], Due: Feb 7th) 
- [ ] Third, put hats on all of the kittens ([small, medium, large], Due: Feb 7th) 
#### What role(s) are you most interested in playing for this campaign? | ¿En que rol estás mas interesado en participar ? pongan sus nombres debajo de las opciones

Building resources
Recruiting and supporting campus leaders
Apply organizing tactics to other parts of your work
#### Which campuses are potential participants in this campaign? Are these technical schools or liberal arts schools? | ¿Qué escuelas, universidades, epsacios de formación son potencialmente buenos para empezar la campaña?

[UNAM en la Facultad de Ingenieria ](http://www.ingenieria.unam.mx/)
[Universidad del Claustro de Sor Juana](http://elclaustro.edu.mx/)

**Comment by penserbjorne** [comment]
Hi Odin, I can help at Facultad de Ingenieria, basing on your plan we can offer a meet with students and talk about:
1. Privacy and neutrality of the web
2. Create content for the web
3. How to contribute with the community

We can find the way to get an auditorium or some space, I've ask the next Monday how to get a space and the requirements.

**Comment by penserbjorne** [comment]
I already asked, we need to write a letter for the director of my area, and need the support from a professor, the professor need to sign the letter, then we can give it the letter to the director. I will try to contact a professor that can give us some support, his name is Juan Carreon, he's a Free Software and Open Source supporter.

Regards!

**Comment by odinm** [comment]
@penserbjorne I talked to the teacher and this week gives us an answer xD

**Comment by odinm** [comment]
@penserbjorne A space was given at a seminar on "Ética hacker y vigilancia" I will talk about the importance of privacy and security on the Internet. It is important that you attend, will be on March 16.

**Comment by penserbjorne** [comment]
@odinm Excelent! :D what I need to attend the event?

**Comment by siclemx** [comment]
Hi Odin I can also help you at UNAM at this first stage, after thta if you want we ca-n export the idea to another colleges or another campus' UNAM in Mexico City. I can talk about why privacy matters and Mozilla mission/technologies about it

**Comment by penserbjorne** [comment]
How is this Odin? Any answer from the teacher? any new? Regards!
