### ISSUE TITLE
Re-engage Mozilla Hungary community in 2016

### ISSUE THREAD

**Issue by flaki** [mozilla/participation-leaders-accountability#24]
## Objective:

Re-gather & engage Mozilla Hungary community in meaningful ways, define tasks and objectives for Q1-Q2 of 2016. Review plans, update communication channels to support information sharing.
## Key Results:
- Have all community tasks enumerated and assigned a designated _champion_ who will follow through with planning/execution
- Transitioned conversations/discussions related to community events & participation from facebook/mailing list to a more open process on the community Discourse
- Started using the [GitHub organization](https://github.com/MozillaHU/) for event & effort planning
- At least 60% of community members started participating in the conversation on those newly opened channels
- Community meetings are happening in a roughly monthly basis
## Related Issues & Links:
- [Bug 1243494: 
  IT Discourse Request: Mozilla Hungary](https://bugzilla.mozilla.org/show_bug.cgi?id=1243494)
- [Mozilla Hungary GitHub organization](https://github.com/MozillaHU/)
## Roles:

Who owns this plan: @flaki
Who is involved: @MozillaHU
## Immediate next steps:
- [x] Survive LS + FOSDEM 2016 _(huge, by Feb 1st)_
- [x] Enumerate community events, tasks, plans _(small, by Feb 7th)_
- [x] Have a _Mozilla Hungarian Community_ discourse channel created _(small, Due: Feb 9th)_
- [ ] Transition community-related discussion to use the MozillaHU Discourse channel _(medium, Due Feb 9th)_
- [ ] Advertise MozillaHU discourse, set up community members with logins _(small, by Feb 14th)_
- [ ] Transition event planning over to [GitHub organization](https://github.com/MozillaHU/) _(medium, by Feb 14th)_
- [ ] Advertise and train GitHub usage among community — step 1: creating an account, filing issues _(small, by Feb 14th)_
- [x] Create Mozilla Hungary Telegram channel for chit-chat _(small, by Feb 14th)_
- [ ] Set up & invite Mozilla Hungary community members with Telegram accounts _(small, Due Feb 21th)_
- [x] Have a community meeting set up after [OSBP meetup](http://www.meetup.com/opensourcebudapest/events/228424462/) _(medium, by Feb 9th)_
- [ ] Have the fate of Education efforts decided, and upon decision to continue effort, come up with a solid plan & champion to follow through (large, Due: March 1st) #

**Comment by flaki** [comment]
[Request fulfilled](https://bugzilla.mozilla.org/show_bug.cgi?id=1243494), [Mozilla Hungarian Community](https://discourse.mozilla-community.org/c/communities/hungary) Discourse channel was created.

**Comment by flaki** [comment]
Started enumerating community plans in:
https://public.etherpad-mozilla.org/p/mozhu2016-plans

Plans [shared](https://www.facebook.com/groups/mobilizerhungary/permalink/1020031431387164/) with community on the facebook group for comments & expansion.

**Comment by brianking** [comment]
Adding myself to monitor / help.

**Comment by flaki** [comment]
The announcement of Mozilla [sunsetting Firefox OS for mobile devices](https://discourse.mozilla-community.org/t/firefox-os-connected-devices-announcement/6864/) causes a lot of [turmoil](https://www.facebook.com/groups/mobilizerhungary/permalink/1020602404663400/?comment_id=1021234847933489&comment_tracking=%7B%22tn%22%3A%22R%22%7D) in the community, especially due to its implications for the [Firefox OS university course](https://wiki.mozilla.org/Firefox_OS/Community/Hungary/Education/Courses/Firefox_OS#Hungarian_Firefox_OS_Education_Award) — will try to work out ways to continue & reconcile the situation at our next community meetup on Tuesday.

**Comment by flaki** [comment]
Had a community meeting after yesterday's [Open Source Budapest Meetup](http://www.meetup.com/opensourcebudapest/events/228424462/) with most of the core community members present.
The meeting went in great spirits, regardless of the saddening news around Firefox OS recently.

We focused on defining the direction for the next 4-6 months, I described the new processes to be implemented _(more open discussion, availability of plans online open for contributions, "champions" process, Etherpad-Discourse-Github workflow)_. We brainstormed about the future plans which were noted on the [planning etherpad](https://public.etherpad-mozilla.org/p/mozhu2016-plans), and are soon to be broken off/announced on their respective discourse threads by the champions.

We agreed on ad-hoc, but regularly held monthly (in-person) community meetings to be held in the future, in addition to the increased online information flow through above mentioned channels, plus the Facebook channel and newly opened Telegram-group.

JSConf Budapest planning were discussed in great detail, and both booth presence and Hungarian community-led projects were discussed and put on the agenda to showcase Hungarian community efforts to a wider audience.

**Comment by ioana-chiorean** [comment]
Adding myself as @flaki 's official mentors ( still )  for mentoring and help.

**Comment by ioana-chiorean** [comment]
> We agreed on ad-hoc, but regularly held monthly (in-person) community meetings to be held in the future

While I agree this is a beautiful thing ( and a bit jealous cause we can't do it in RO) I wonder how you guys plan to do it form the mozillians that live outside of Budapest.

**Comment by flaki** [comment]
@ioana-chiorean you are perfectly right, but frankly, I'm trying to revamp the whole of the Hungarian community from the ground up, and seed it with the Budapest-based community first. Mozillians from around the country are no less important, but that has to wait until we have a solid core.

**Comment by flaki** [comment]
In other news, it was an eventful week! I had few more meetings (and one scheduled with @brianking) wrt Firefox OS & Education efforts. We are continuing the transition to more canonical channels for communication, and organizing events & presences (like JSConfBp).

**Comment by flaki** [comment]
Also, revised objectives to be more reflective of the efforts happening.

**Comment by flaki** [comment]
[Working](https://public.etherpad-mozilla.org/p/mozillahu-education-2016) on revamping @mozillahu [education](https://github.com/MozillaHU/education/blob/master/FALL_SEMESTER_2016.md) efforts with @Krisztian666 & @brianking.

**Comment by ioana-chiorean** [comment]
> Working on revamping @mozillahu education efforts with @Krisztian666 & @brianking.  

:raised_hands:  :clap:

**Comment by flaki** [comment]
Wrote up some info about our fledgling Webmaker-inspired diversity web development workshop, [Happy Code Friends](https://github.com/MozillaHU/happycodefriends/).

**Comment by flaki** [comment]
Conferencing, lot more work on Happy Code Friends and finalizing the details of the @mozillahu  [Hackerlounge](https://github.com/MozillaHU/hackerlounge).

**Comment by brianking** [comment]
Maybe we can close this with a summary of current status, and open a new issue for 2017?
