### ISSUE TITLE
Campus campaign in Nairobi, Kenya [DRAFT]

### ISSUE THREAD

**Issue by AI-DennisNdegwa** [mozilla/participation-leaders-accountability#26]
## Objective:

To kick off the campus campaign and strengthen Mozilla presence in Nairobi, Kenya. 
## Key Results:
- [Measure of success 1 -- Talks given in at least four campuses] 
- [Measure of success 2 -- At least 20 new volunteers making contributions by mid year] 
- [Measure of success 3 -- Established Mozilla presence in at least four campuses] 
## Roles:

Who owns this plan: @denomain
Who is involved: Mozilla Kenya Community
                                - @chanditome 
## Immediate next steps:
- [x] Contact all the targeted campuses and their administrators for permission to engage ([medium], Due: Feb 29th) 
- [ ] Give talks, create awareness about privacy and the Mozilla volunteers program ([large], Due: March 31st) 
- [ ] Get individuals to pick an area of interest ([large], Due: April 15th) 
#### Roles that I am interested in playing for this campaign.

Contact the administrators at each campus
Give talks
Recruiting and supporting new Mozillians and campus leaders
#### Campuses that are potential participants in this campaign.

IAT group of schools (technical schools), St. Paul's University (technical and liberal schools), Kenyatta University (technical and liberal schools)

The plan is to begin with the technical schools and move on to others later.
#### Method of engagement.

Talks in classrooms, Mozcoffes
#### Team members that need to be engaged.

W.I.P
#### Method of engagement.

Call to action on Mozilla Kenya page.
#### Tactics that will be used to achieve goals.

Physical visits to the several campuses

**Comment by chanditome** [comment]
@denomain let's do this!

**Comment by AI-DennisNdegwa** [comment]
@chanditome glad to see you here. Will keep you updated.
