### ISSUE TITLE
Madagascar - Connected Devices

### ISSUE THREAD

**Issue by mariot** [mozilla/participation-leaders-accountability#27]
# Objective:

Mozilla Madagascar gives a proposal for Connected Devices.
# Key Results:
-  At least 2 members help out with Connected Devices
-  We have at least 1 further meetup to brainstorm on use cases / proposals for Connected Devices
# Related Issues & Links:
# Roles:

Who owns this plan: @mariot
Who is involved: Mozilla Madagascar Community
# Immediate next steps:
- [x] Tell community on the status of Connected Devices (medium, Due: Feb 13th)
- [x] Find 2 people interested in organizing a meetup around CD (medium, Due: Feb 15th)
- [ ] Organize a meetup (large, Due: Mar 12th)
- [ ] Check up with @ioana-chiorean for the accountability part

**Comment by flaki** [comment]
Subscribing! Good luck with those, let me know if you need any help! ;)

Also be sure to check out the [AMA with Ari Jaaksi, Svp. of Connected Devices](https://discourse.mozilla-community.org/t/ask-me-anything-with-ari-jaaksi-and-other-connected-devices-follow-up/7016) later this week! ;)

**Comment by ioana-chiorean** [comment]
Can you add one [ ] for the accountability part with me? Like check up with Ioana for the accountability part - in this was we ensure the results are visible and shared.
