### ISSUE TITLE
Mozilla Madagascar Online Presence

### ISSUE THREAD

**Issue by mariot** [mozilla/participation-leaders-accountability#28]
# Objective:

Mozilla Madagascar has a strong online presence
# Key Results:
-  At least 300 likes on Facebook
-  At least 1 article every two weeks on the blog
# Related Issues & Links:

https://mozillamadagascar.wordpress.com
https://twitter.com/mozillamg
https://www.facebook.com/mozmada
# Roles:

Who owns this plan: @mariot
Who is involved: Mozilla Madagascar Community
# Immediate next steps:
- [x] Tell community on the status of online presence (medium, Due: Feb 13th)
- [x] Setup the Facebook account (large, Due: Feb 13th)
- [x] Find 2 people interested in curating the Twitter and Facebook accounts (medium, Due: Feb 15th)
- [x] Check up with @ioana-chiorean for the accountability part

**Comment by ioana-chiorean** [comment]
Can you add one [ ] for the accountability part with me? Like check up with Ioana for the accountability part - in this was we ensure the results are visible and shared.

**Comment by ioana-chiorean** [comment]
Thank you! :tada:
I am a strong social media user - if you need help on this do not hesitate to ping me.

**Comment by mariot** [comment]
Thanks Ioana!
Will do :+1:

**Comment by ghost** [comment]
Great job Mariot !
You are really doing well !
I want just to let you know that the URLs in the Related Issues & Links are not working.
Have a great weekend !
