### ISSUE TITLE
Organize Mozilla Madagascar FSA meetup

### ISSUE THREAD

**Issue by mariot** [mozilla/participation-leaders-accountability#29]
# Objective:

Mozilla Madagascar FSAs are organized and have help from Reps
# Key Results:
-  At least 5 new FSA members
-  We have at least 2 FSA events
# Related Issues & Links:
# Roles:

Who owns this plan: @mariot
Who is involved: Mozilla Madagascar Community
# Immediate next steps:
- [x] Tell community on the status of FSA (medium, Due: Feb 13th)
- [x] Find 3 people interested in working with FSAs (medium, Due: Feb 15th)
- [ ] Organize a meetup (large, Due: Mar 12th)
- [ ] Check up with @ioana-chiorean for the accountability part

**Comment by ioana-chiorean** [comment]
Can you add one [ ] for the accountability part with me? Like check up with Ioana for the accountability part - in this was we ensure the results are visible and shared.
