### ISSUE TITLE
Face 0 campus campaign The Netherlands

### ISSUE THREAD

**Issue by Timmaks** [mozilla/participation-leaders-accountability#3]
## Objective:

Face 0 campus campaign The Netherlands
## Key Results:
- Get a team together on a campus
- The team start on working how to do the campus campain on their university
## Related Issues & Links:

[Reference meta issues, past issues or other people's issues if you might be working together] #
## Roles:

Who owns this plan: @timmaks
Who is involved: 
## Immediate next steps:
- [x] Contact a potentional campusleader (Lorenzo], Due: Feb 7th) 
- [ ] assemble a team together with Lorenzo, Due: Feb 14th) 
- [ ] Planning a meeting on the campus, Due: Feb 28) 
#### What role(s) are you most interested in playing for this campaign?

Recruiting and supporting campus leaders
#### Who are the stakeholders you need to engage?

Lorenzo
#### How are you going to do that engagement?

Having a call with heim about the campus campain and look into his connection on that campus
#### Who are the team members you need to engage?

?

**Comment by Timmaks** [comment]
Lorenzo is going to contact some students to form a team.

**Comment by loreV** [comment]
I have contacted three students from uni and I am now waiting for their response.

**Comment by Timmaks** [comment]
@loreV there is now a website live with info for this campaign, https://takebacktheweb.mozilla.community/, can you set up a doodle (or simular) to arrange a meeting with your team

**Comment by Timmaks** [comment]
Ok start again.
Had a good meeting with @loreV and made contact with the team from a university in Tilburg.  

Next arrange a meeting with that team to learn from them
