### ISSUE TITLE
WoMoz Cameroon

### ISSUE THREAD

**Issue by estellenina** [mozilla/participation-leaders-accountability#36]
# WoMoz Cameroon
# Objective:

Organize WoMoz  Cameroon to increase the participation of women by teaching Mozilla tools to them and helping them to be well involved in Mozilla Cameroon activities 
Building a strong WoMoz Cameroon Program
Be involved in Technovation Challenge in cameroon
# Key Results:

• Having at least 10 active WoMoz Contributors in different regions of Cameroon 
• Increase the numbers of contributors in different others programs like FSA, MDN, Advocacy, TeachTheWeb
• Having at least 3 projects realize by WoMoz in Cameroon
• Social Media metrics, articles and blogposts published
# Roles:

Who owns this plan: @estellenina
Who is involved: @dorothydaf @desydanga @Izanefg @MinetteZongo @Doualanow @Lydienne @NellySiabo @Cdjafa @bepolite @valdesjo77 @steevetp @ibr4him2011 and Mozilla Cameroon.
# Immediate next steps:

• Technovation Sensitization, recruiting time and training sessions for mentors, coaches and students with all WoMoz members ( since January 9th)
• Talk with Cameroonian WoMoz member for a debrief after Leadership summit (Due to February 23rd)
• Formulate a strong suitable plan for WoMoz activities around the country (Due to February 27th)
• Sharing final plan with Mozilla Cameroon and starting the WoMoz campaign around the country (Due to February 28th)
# Specific WoMoz campaign planning questions:
### _What role(s) are you most interested in playing for this campaign?_

Recruitment of new contributors and help forming new groups of WoMoz in regions 
Strategic planning for success of the campaign.
### _Which campuses are potential participants in this campaign? Are these technical schools or liberal arts schools?_

For the first semester 2016, we will try to work with campuses in Douala, Yaounde, Ngaoundere, Buea, Bamenda and Maroua.
Here are some examples
- In Yaounde we will held a workshop on March 1st  at Ministry of Communication of Cameroon under the theme “Women-Mobile Applications- Social Media and Privacy”. At this workshop all WoMoz regional coordinators will present and lead training sessions
- In  Ngaoundere, WoMoz member will produce within March to May, a video program on touristic values of Northen Regions by using Pop Corn, a webmaker tool. 
- In differents regions of the country, in March, Womoz members will set up some meetup for sharing their experiences on International Women Day week
- In  differents regions of the country working session with Technovation teams will take place due to April 21st.
  ### _Who are the stakeholders you need to engage?_
  
  • IT Club/Firefox Club leads of the college. 
  • Firefox Student Ambassadors. 
  • College Administration. 
  ### How are you going to do that engagement?
  
  • By organizing events. 
  • By mentoring women and girls in STEM 
  • Me, Reps and specialized leaders of Mozilla Cameroon will merge our efforts 

• Prepare graphical/visual materials which explain topics we want to share
• Give short talks about importance of programs of Mozilla, of joining Mozilla as a contributor
• Create survey form templates for capture what the students learned
• Organize small competitions for sharing special goodies or swag of Mozilla ought to develop interaction.

**Comment by emmairwin** [comment]
cc @larissashapiro
