### ISSUE TITLE
Campus Campaign Cameroon

### ISSUE THREAD

**Issue by desydanga** [mozilla/participation-leaders-accountability#37]
**Objective:**
- Mozilla Cameroon will run a Campus Campaign within University Games (April-May) in which converge about 20 universities and high schools of Cameroon
- Mozilla Cameroon will train young people about Mozilla privacy, advocacy, connected devices and will present different possibilities of contributions at Mozilla
- Mozilla Cameroon will explain new strategy of the community because Firefox OS is pivoting to Connected Devices

**Key** **Results:**
- Having at least 10 new active FSA Contributors in different regions of Cameroon 
- Increase the numbers of contributors in different others programs like WOMOZ, MDN, Advocacy, TeachTheWeb
- Social Media Metrics, articles and blogposts.

**Roles:**
_Who owns this plan:_ @desydanga
_Who is involved:_ @dorothydaf @hervekgh @Izanefg @bepolite @ngesbrian @Sergecodd and Mozilla Cameroon.

**Immediate next steps:**
- Talk with FSA club lead and regional coordinator in Cameroon for designing a good plan of action for university games. Due to Feb 29th
- Formulate a strong suitable plan for hackathons within different local communities Due to Feb 29th
  merge all ideas of FSA club lead and regional coordinators in Cameroon for setting a synchronise agenda Due to Feb 29th
  **
  Specific campus campaign planning questions:**
  _What role(s) are you most interested in playing for this campaign?_
- Recruitment of new contributors and help forming new clubs in 3 regions not yet covered by Mozilla Cameroon
- Strategic planning for success of the campaign.

_Which campuses are potential participants in this campaign? Are these technical schools or liberal arts schools?_
Universities involved in the campaign are about 10 known as State's universities , about 15 specialized and technical schools and 10 from private sector. These different universities and school are based in one of the 10 regions of Cameroon.

**How are you going to do that engagement?**
- By organizing events
- By a one to one mentoring of FSA club lead and coordinators
- Me,Reps and specialized leaders of Mozilla Cameroon will merge our efforts
  **
  What are some tactics you will pursue to achieve your goals?**
- Prepare graphical/visual materials which explain topics we want to share
- Give short talks about importance of programs of Mozilla, of joining Mozilla as a contributor
- Create survey form templates for capture what the students learned
- Organize small competitions for sharing special goodies or swag of Mozilla ought to develop interaction.

**Comment by NgesBrian** [comment]
This  is a great plan.

**Comment by emmairwin** [comment]
(added connected devices tag, as that is also part of this issue)

Reviewing this with Dorothee
1) Need to understand how to talk about Connected Devices  (transition from Firefox OS).   We really need to be able to answer the question "what is the difference between connected devices, and FFOS  .
2) What would a booth look like that shares more about Mozilla Tools, and Connected Devices.
3) We need flyers & documents for sharing at the University Games.
4) What topics, conversations and materials 'fit' under Campus Campaign?
