### ISSUE TITLE
Connected Devices Cameroon

### ISSUE THREAD

**Issue by Dorothydaf** [mozilla/participation-leaders-accountability#38]
# **# Objectives:**
- Mozilla Cameroon will launch a Social media campaign on Connected Devices information within February and Junebecause Firefox OS is pivoting to Connected Devices and will present different possibilities of contributions at Mozilla. Adding to that, a Blog post Constest will be run within April and June on Connected Devices.
- Mozilla Cameroon will run a Localization Camp (L10n Camp) for bringing a diversity content for Connected Devices  in June ought to have content in about 10 local languages in Cameroon (The country has more than 200 local languages)
- Mozilla Cameroon will launch a MDN group in April ought to train young people about Mozilla dev tools and technics, Webmaker, Bugzilla and Github uses, Mozilla privacy, advocacy, connected devices 

**#Key Results:**
- Having at least 10 new active MDN &L10n  Contributors in different regions of Cameroon 
- Increase the numbers of contributors in different others activities like bloggers, Advocacy contributors, TeachTheWeb contributers
- Social Media Metrics, articles and blogposts, MDN &L10n groups setup

**# Roles:**

Who owns this plan: @dorothydaf
Who is involved:  @Izanefg @bepolite @valdesjo @nges_brian @Serge_codd and Mozilla Cameroon.

**# Immediate next steps:**
- Talk with Mozilla regional coordinator in Cameroon for designing a good plan for launching MDN &L10n activites. Due to March 7th
- Formulate a strong suitable plan for hackathons and Localization camp  Due to March 7th
- Merge all ideas for setting a synchronise social media and Blog post campaign Due to March 15th
# **Specific Connected devices planning questions:**
## What role(s) are you most interested in playing for this campaign?
- Recruitment of new contributors and help forming MDN &L10n  groups by Mozilla Cameroon
- Strategic planning for success of the  Social Media and Blog posts campaign.
## Which campuses are potential participants in this campaign? Are these technical schools or liberal arts schools?

For the first semester 2016, we will try to work with campuses in Douala, Yaounde, Ngaoundere, Buea, Bamenda and Maroua.
## How are you going to do that engagement?

By organizing events:  MDN Hackathons & L10n Camp in June-July
By a one to one mentoring Mozilla Cameroon regional coordinators
Me, Reps and specialized leaders of Mozilla Cameroon will merge our efforts
## What are some tactics you will pursue to achieve your goals?

Prepare graphical/visual materials which explain topics we want to share
Give short talks about importance of programs of Mozilla, of joining Mozilla as a contributor
Create survey form templates for capture what the Mozillians learned
Organize small competitions for sharing special goodies or swag of Mozilla ought to develop interaction.

**Comment by emmairwin** [comment]
Discussion with Dorothee, things that would help this team be successful

1) We need contact - "web content for MDN group"    (chris mills?)
2) Stickers for localization camp  
3) Someone to talk us through this event that are experts in areas of localization, connected devices and mDN, are we on mark for goals? what resources can you provide?
