### ISSUE TITLE
Awareness of new strategy and path for Connected Devices

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/participation-leaders-accountability#43]
## Objective:
- all local mozillians are aware of the change for Firefox OS and the new plan around Connected Devices
- At least one proposal sent from these people contacted through the initiatives. 
## Key Results:
- [ ] Held a MozCoffee to let the local mozillians now the new strategy for Connected Devices
- [ ] Participate in different meetups & organizations to promote the new strategy and make people things about their our proposals for Connected Devices.

Related Issues & Links:
- none yet

Who owns this plan: @ioana-chiorean
Who is involved: @bebef1987
## Immediate next steps:
- [ ] Decide on the meetups that match our path ([small], Due: March 6th)
- [ ] Decide on the organizations that match our path ([small], Due: March 6th)
- [ ] Check which events are in the area in the near future and join them ([medium], Due: March 20th)

**Comment by Jobava** [comment]
I'd like to be involved in this plan too.
