### ISSUE TITLE
Campus Campaign in (some) universities in Romania 

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/participation-leaders-accountability#44]
## Objective:
- all local mozillians are aware of the details of Campus Campaign 
- At least one university contacted is ok to participate in the campiagn
## Key Results:
- [ ] A MozCoffee is organized to let the local mozillians know details of the Campaign
- [ ] All materials available for Campus Campaign are localize in Romanian
- [ ] Universities are in touch with the community

Related Issues & Links:
- none yet

Who owns this plan: @ioana-chiorean
Who is involved: @bebef1987
## Immediate next steps:
- [ ] Get all materials about campus campaign ([small], Due: March 6th)
- [ ] Localize the materials  ([small], Due: March 6th)
- [ ] Contact universities ([medium], Due: March 20th)

**Comment by Jobava** [comment]
Please add me to this plan as an involved person.
