### ISSUE TITLE
Connected Devices online/offline publicity

### ISSUE THREAD

**Issue by Pensacola** [mozilla/participation-leaders-accountability#45]
## **Objective:**
- Increase blog posts/articles about the Connected devices plan in Romania and not only. 
  (Per @fahrulrazy, he is planning to write a blog post/article for Indonesia too).
## **Key Results:**
- Organize at least one online/offline meetup for gathering proposals and promote the new CD plan to community and/or potential contributors.
## **Related Issues & Links**:
- [Mozilla and IoT projects](http://pensacola-tech.com/pensacola/2016/03/08/mozilla-and-iot-projects/)
- [Mozilla Connected Devices](http://osom.ro/2016/03/mozilla-and-connected-devices/)
- [Firefox OS: The Next Steps](https://fahrulrazy.wordpress.com/2016/03/23/firefox-os-the-next-steps/)
- [Connected Devices](https://bitnesia.com/firefox-os-2-6-mozilla-connected-devices.html)
## **Roles:**

Who owns this plan: @pensacola
Who is involved: @ioana-chiorean
## **Immediate next steps:**
- [x]  Write a blog post about CD ([small], Due: March 7th)
- [x]  Find more contributors that are willing to write blog posts/articles about CD ([medium], Due: March 25th)
- [x] Check existing events in Bucharest and join them in order to increase our presence  ([medium], Due: March 30th)

**Comment by mfachrulrazy** [comment]
I would like to join this in this plan, and maybe we could add Indonesia as the objective

**Comment by mfachrulrazy** [comment]
Here's my blog post about firefox os and connected devices: https://fahrulrazy.wordpress.com/2016/03/23/firefox-os-the-next-steps/
and later will be post on one of our online news in Indonesia, and I will comment in this Issue

**Comment by mfachrulrazy** [comment]
Here's an article from online media in my country talk about Connected Device: https://bitnesia.com/firefox-os-2-6-mozilla-connected-devices.html
