### ISSUE TITLE
Mozilla Tunisia KickStart

### ISSUE THREAD

**Issue by ghost** [mozilla/participation-leaders-accountability#47]
![kickstart](https://cloud.githubusercontent.com/assets/1727511/13355757/33128650-dca2-11e5-9b92-3d9c7a1fa0f8.png)
## Objective:
- Growing the local community with new active mozillians 
- Every new mozillian have to join one of the teams in Mozilla Tunisia 

-- Speaking Team ( The mentor of this team is @zaafouriFF )

-- Teaching Team ( The mentor of this team is @mermi )

-- Coding Team ( The mentors of this team are @anefzaoui & @MedMack )

-- Localisation Team ( The mentors of this team are @asmasma21 & @SynergySINE )
## Key Results:
- 15 new active mozillians in Tunisia
- Defining the communication channels and tools
  **Github** : For coding projects and teams follow up
  **ML** : For events and important annoucements
  **IRC** : For large group discussions/meetings
  **Discourse** : Discussisng community topics
  **Telegram** : Quick chats for community members
## Related Issues & Links: ( #MozTnKickStart )

[Preparation Pad](http://pad.mozilla-tunisia.org/p/meeting-31-01-2016)
[Reps Event](https://reps.mozilla.org/e/mozilla-tunisia-kickstart/)
[Topic in discourse](https://discourse.mozilla-community.org/t/mozilla-tunisia-kickstart-event-planning/6822)
[Facebook](https://www.facebook.com/search/top/?q=%23%E2%80%8Emoztnkickstart%E2%80%AC)
[Twitter](https://twitter.com/hashtag/moztnkickstart?src=hash)
[Article 1 about this event](https://africa.mozilla.community/en/weekly-round-up-36/)
[Article 2 about this event](https://africa.mozilla.community/en/weekly-round-up-35/)
## Roles:

Who owns this plan: @moztn
Who is involved: @zaafouriFF @mermi @anefzaoui @MedMack @asmasma21 @SynergySINE @Missty125
## Immediate next steps:
- [x] Creating Get-involved guide for the new mozillians [Here](https://github.com/moztn/Get-Involved)
- [x] Creating Github Repo for the Speaking Team [Here](https://github.com/moztn/Speaking-Team)
- [x] Creating Github Repo for the Localisation Team [Here](https://github.com/moztn/Localization-Team)
- [x] Creating Github Repo for the Teaching Team [Here](https://github.com/moztn/Education-Team)
- [x] Creating Github Repo for the Coding Team [Here](https://github.com/moztn/Coding-Team)
- [x] Preparing the internal Brainstorming Event
  ## Now let us share with you the result of this work

![result](https://cloud.githubusercontent.com/assets/1727511/13357853/b92d8474-dcac-11e5-9e77-2295f8815c81.jpg)

**Comment by ghost** [comment]
Cc @williamq & @brianking ,
Can you please add yourselves as mentors ?
& Thanks

**Comment by ghost** [comment]
Cc @rosanardila ,
Can you please add the " Campus Campaign " Label to this issue 
& Thanks

**Comment by brianking** [comment]
Great plans @ZaafouriFF ! Where/how would you like us to add ourselves as mentors?

**Comment by ghost** [comment]
Thanks @brianking !
Hmm.. How or Where ? 
Honestly I don't know
Maybe adding your name to the participants list or subscribing to the notifications to be updated.
See you soon in Tunisia 
Have a nice day
