### ISSUE TITLE
Mozilla Tunisia Brainstorming

### ISSUE THREAD

**Issue by ghost** [mozilla/participation-leaders-accountability#48]
## Objective:
- Fixing a first draft of a road map with the new mozillians for 2016 
## Key Results:
- Ideas for events to organise
- Participation in some local events
## Related Issues & Links:

 Mozilla Tunisia KickStart #47 
[Brainstorming Pad](http://pad.mozilla-tunisia.org/p/brainstorming-meetup)
[Preparation Meeting](https://discourse.mozilla-community.org/t/mozilla-tunisia-brainstorming-meetup/7138)
[Reps Event](https://reps.mozilla.org/e/mozilla-tunisia-brainstorming-meetup/)
[Facebook](https://www.facebook.com/search/top/?q=%23%E2%80%8Emoztnkickstart%E2%80%AC)
[Twitter](https://twitter.com/hashtag/moztnkickstart?src=hash)
[Article about this event](https://africa.mozilla.community/en/weekly-round-up-38/)
## Roles:

Who owns this plan: @moztn
Who is involved: @zaafouriFF @mermi @anefzaoui @MedMack @asmasma21 @SynergySINE @Missty125 @marwendoukh @pendow
## Immediate next steps:
- [x] nominating some interesting events that we can organise or where we can participate
- [x] Preparing for the SuMo Sprint in Tunisia
- [x] Preparing The Github training 
  ## Now let us share with you the result of this work

![brainstorming](https://cloud.githubusercontent.com/assets/1727511/13364798/479ba1cc-dcd1-11e5-9a2e-ea1824fc3bee.jpg)

**Comment by ghost** [comment]
Cc @rosanardila ,
Can you please add the " Community Sync " Label to this issue
& Thanks

**Comment by SynergySINE** [comment]
- Preparing for the SuMo Sprint in Tunisia
- Preparing The Github training

Both done @ZaafouriFF

**Comment by ghost** [comment]
Thanks @SynergySINE 
Done !!
