### ISSUE TITLE
Localization Process

### ISSUE THREAD

**Issue by alvarmaciel** [mozilla/participation-leaders-accountability#5]
Hi,
I open this issue to accord a localization process for the resources and the process himself of the campus campaign.
Some Ideas:
- There is a lot of information in the slides of each session. If we can have that in the mozilla wiki, we can make wiki page of several lang with the names_local url
- It is really important to have images and pdf on SVG format. That way we can change strings easy

**Comment by Pike** [comment]
I don't have a better suggestion at this point, but maintaining localized content on wikimo is probably not good. Sure, we can create a bunch of wiki pages in different languages, but that's not a powerful infrastructure for localized content.

**Comment by alvarmaciel** [comment]
@Pike I agree with you, that's not a powerful infrastructure for localized content. But I think that Mozilla Wiki is the entry door for many of us. We can have there a little bit of information (in several languajes), a road map, links to the resources and to the localization process of it.

**Comment by daas88** [comment]
My suggestion would be to place the localized content in Mozilla Hispano's wiki. Other locales could do the same in their own wikis.

**Comment by ioana-chiorean** [comment]
Are those already up accessible?
