### ISSUE TITLE
Introducing IoT and Firefox for Connected Devices to my University and MozGirls Evolution & Teaching the Web

### ISSUE THREAD

**Issue by AsmaSwapna-zz** [mozilla/participation-leaders-accountability#51]
# Objective 1
- Make awareness about IoT and Firefox OS among and the enthusiasm among the students of the Engineering faculty 
- Grooming the newest idea and modeling with IoT and connected device track with Mozilla contributors from ICT department of the campus
# Objective 2

Organize the female contributors in the local area and empower them for leading next bunch of female active contributors
# Objective 3

Initiate the very first Mozilla activities inaugurating new Firefox club with the permission of University committee (Campus Campaign). 
# Objective 4
- Introducing 'teach the web' and Mozilla Clubs manifesto
- Organize the local Mozilla Club captains and being an Active RC
# Key Results 1
- Some sessions and workshops from Intro to IoT to hands on device hacking 
- Several promising projects of IoT based on Mozilla open web from the tech students
- Active contributor in the track of Connected Devices
- Mass awareness among people joining the workshops and sessions
# Key Results 2
- Active female contributors monitoring, leading and engaging more women in Mozilla mission.
- Female tech enthusiast hacking the IoT and connected device track.
- Mass participation and growth of MozGirls community
# Key Results 3
- Improved relationship among the local contributors
- Activate local contributors
- New engagement in the community
# Key Results 4
- Regular Meetings and more interaction to support the club captains
- Planning and Working towards the next six months goal for the clubs
- Avail the resources and evaluation of activities biweekly
# Related Issues and Links

> Working on the Issues

[https://wiki.mozilla.org/WoMoz](url)
[https://teach.mozilla.org/](url)

Who owns this plan: @AsmaSwapan
Who is involved: Not Yet
# Immediate Next Steps

> Objective 1
- [ ] Decide on involved Mozillians and having agendas
- [ ] Decide on the next hackathon and session schedule
- [ ] Avail the resources for the events and create enthusiasm among the target group
- [ ] Join the events already planned in this area and get knowledge required on making the plan successful.

> Objective 2
- [ ]  Hold the online and offline meetings with the MozGirls and plan for the mid-term
- [ ]  Talk about the WoMoz missions and newly to be formed MozGirls team in the running local events and create awareness
- [ ] Create GitHub issues for the next big move from the community and work on the agenda with the leads
- [ ]  Execute a next big move from the MozGirl leads to engage and empower more women enthusiasts
- [ ]  Explore female teche contributing in the IoT for Connected device tracks and want hack the track to perform workshops

> Objective 3
- [ ] Gather the scattered local contributors and FSA as the University and apply for the Firefox Club
- [ ] Join the running Campus related Campaigns with the club and members
- [ ] Engage the FSAs with regional clubs and members and exchange experience and mentor them
- [ ] Initiate plan for very first MozAwareness and MozCoffee event plannings

> Objective 4
- [ ] Meet the club captains in the region and set the mid-term goals for the clubs
- [ ] Contact the global support and represent the goals for next 6 months
- [ ] Execute the planning and evaluate the biweekly updates with Club Captains in online meetings
- [ ] Start the web literacy curriculum with at least two of the local high schools within next 3 months. Continuing club activities on a regular basis and evaluate the achievements in next 3 months. Diclose Leadership opportunities to the active club captains and innitiate more clubs on school level run and evaluated by themselves.

**Comment by srdesh** [comment]
Great job @AsmaSwapna ;)
