### ISSUE TITLE
Mozilla Tunisia SUMO L10N Arabic Sprint

### ISSUE THREAD

**Issue by ghost** [mozilla/participation-leaders-accountability#52]
## Objective:
- A meetup for the local Tunisian community to localize the SUMO knowledge base to the Arabic locale.
## Key Results:
- Localising 60 Articles
- Introducing the tools to new SuMo contributors
- Assisting the new contributors in their first training with l10n 
## Related Issues & Links:

Mozilla Tunisia KickStart #47 
Mozilla Tunisia Brainstorming #48 
[Discourse Topic](https://discourse.mozilla-community.org/t/mozilla-tunisia-sumo-l10n-arabic-sprint/7330/)
[Pad of the event](http://pad.mozilla-tunisia.org/p/sumo-sprint)
[Facebook](https://www.facebook.com/hashtag/moztnsumosprint?source=feed_text&story_id=1096112927105443&pnref=story)
[Twitter](https://twitter.com/hashtag/MozTnSUMOSprint?src=hash)
[Reps Event](https://reps.mozilla.org/e/sumo-localization-sprint-1/)
[Article in SUMO blog](https://blog.mozilla.org/sumo/2016/03/11/event-report-1st-sumo-l10n-sprint-in-tunisia/)
## Roles:

Who owns this plan: @moztn
Who is involved: @zaafouriFF @mermi @MedMack @asmasma21 @SynergySINE @Missty125 @marwendoukh
## Immediate next steps:
- [ ] One or two virtual sprints ([small], Due: Mars 13th) 
- [x] Reviewing all the localisation done 
- [ ] Preparing the local localisation team meeting ([medium], Due: Mars 20th) 
  ## Now let us share with you the result of this work

![sumo](https://cloud.githubusercontent.com/assets/1727511/13390175/0227be84-decd-11e5-80c7-ca1ebc926ac9.jpg)

**Comment by ghost** [comment]
@SynergySINE did the training thanks to the @moztn internship Cc @williamq

**Comment by SynergySINE** [comment]
Reviewing all the localisation : done @ZaafouriFF

**Comment by ghost** [comment]
Updated !
Thanks @SynergySINE

**Comment by SynergySINE** [comment]
Article up on SUMO blog : [Event Report: 1st SUMO l10n sprint in Tunisia](https://blog.mozilla.org/sumo/2016/03/11/event-report-1st-sumo-l10n-sprint-in-tunisia/)

**Comment by ghost** [comment]
Adding the SUMO article Thanks @SynergySINE !
