### ISSUE TITLE
Mozilla Tunisia planning for connected devices

### ISSUE THREAD

**Issue by ghost** [mozilla/participation-leaders-accountability#53]
## Objective:
- Planning for Mozilla Tunisia involvement in the connected devices plan
## Key Results:
- Knowing more about the strategy of Mozilla concerning the connected devices
- Getting involed in connected devices projects with other Mozilla communities 
## Related Issues & Links:
- Mozilla Tunisia Kickstart #47 
- Mozilla Tunisia Brainstorming #48 
## Roles:

Who owns this plan: @moztn
Who is involved: @zaafouriFF @mermi @anefzaoui @MedMack @asmasma21 @SynergySINE @Missty125
##### Design Kit: The Course for Human-Centered Design
- [x] Creating Mozilla Tunisia Group in the Course for Human-Centered Design [Here](https://novoed.com/design-kit-q1-2016/oe/#!/teams/134695/profile) 
- [x] Submitting the first assignment 
- [ ] Inviting more members to the course ([small], Due: Mars 6th) 
- [ ] Preparing the second assignment ([medium], Due: Mars 9th) 
##### Local plan:
- [x] Contacting MozillaVR guy in Tunisia (Bechir) and inviting him to the community
- [ ] Getting more details in WoT needs for the projects with @ajst ([medium], Due: Mars 3rd) 
- [ ] planning a call with Japan or Taiwan members to ask for help in our local projects ([medium], Due: Mars 10th)
##### international plan:
- [x] Contacting @williamq for contacts and more updates about the connected devices plan for Mozilla
- [x] Attending a meeting with Mahmood ( Mozilla Jordan ) and Mr. John Bernard about the connected devices in Africa and MENA region ([medium], Due: Mars 4th)
- [ ] Testing JanOS [Website from here](http://janos.io/) ([medium], Due: Mars 20th)
- [ ] Testing firefox OS on RaspberryPi [Here](https://wiki.mozilla.org/Fxos_on_RaspberryPi) ([medium], Due: Mars 27th)

**Comment by SynergySINE** [comment]
Contacting MozillaVR guy in Tunisia (Bechir) and inviting him to the community : done @ZaafouriFF

**Comment by ghost** [comment]
Updated done, Thanks @SynergySINE 
Also,  Attending a meeting with Mahmood ( Mozilla Jordan ) and Mr. John Bernard about the connected devices in Africa and MENA region --> Done
