### ISSUE TITLE
DRAFT: Indonesia campus campaign

### ISSUE THREAD

**Issue by ariestiyansyah** [mozilla/participation-leaders-accountability#6]
## Goal:

[One line goal description] 
- Community Growth: Get 10 active supporters in each campusses group
- Product/Adoption: 100 install of firefox in each campusses
- Technology: 2 or more addons 
## Campusses:
- Dian Nuswantoro University (UDINUS) 
- Sekolah Tinggi Perpajakan Indonesia
- Sepuluh Nopember Institute of Technology (ITS)
- Binus University
- Universitas Hasanuddin (UNHAS)
- Universitas Islam Negeri Alauddin Makassar(UIN)
- Universitas Negeri Makassar (UNM)
## Success:

  [What would success look like] 
- 2 or more addons published in addons.firefox.org by student from the campus
- Recruit 3 more active FSA from Indonesia
## Related Issues & Links:

[Reference meta issues and past issues] #
(coming)
## Roles:

Owner: @ariestiyansyah 
Involved: @kelimuttu @alamanda @dikyarga 
## Required:
- [ ] List down the FSA from each campuses that we targeted (dead line: 7 February 2016) 
- [ ] Approach potential established community in campuses to support our campaign (dead line: 7 February 2016)
- [ ]()

**Comment by alamanda** [comment]
I think we need to list the name of those campuses to get a clear goal

**Comment by dikyarga** [comment]
I think we already do that, as i remember :
1. Udinus
2. Sekolah Tinggi Perpajakan Indonesia
3. ITS

right ?

**Comment by alamanda** [comment]
And Binus. I understand that we talked about it. But it doesn't show in this github issue. Hence the suggestion.

**Comment by RizRiyz** [comment]
@alamanda I just added the campusses list in this issue. Like you said before BINUS will be optional or replacement for other university.

**Comment by alamanda** [comment]
Nice!
Then, my suggestion of the goals will be: 
Community Growth: Get 10 active supporters in three out of four campuses on the list
Product/Adoption: 100 Firefox install in three out of four campuses on the list
Technology: Two or more addons--will it be from each campus? or minimum 2 addons from whichever campus on the list? 

Also, should we have time-frame in achieving these goals mentioned in this github issue? When is the target to achieve those goals?

**Comment by RizRiyz** [comment]
Agree! 
Let's setup the time-frame or timeline for goals.

I'll start from Sekolah Tinggi Perpajakan Indonesia
Programming: 
- February - March: Event Plan (holiday)
- April: Preparation campus campaign event
- May: Technology and Educational event for tax students

Benchmarks:
- End of June: 2 or more addons published on Addon marketplace 
- End of June: 100+ firefox installation in Sekolah Tinggi Perpajakan Indonesia

**Comment by RizRiyz** [comment]
any update from @kelimuttu @dikyarga ?

**Comment by kelimuttu** [comment]
I'll add the plan for ITS: 
- February : Event plan (contacting local ambassador)
- March : Preparation 
- April : Campus campaign

Benchmarks:
End of May: Recruite 2 more active FSA from Surabaya
End of May: 100+ firefox installation in ITS

@ariestiyansyah can I have the list of FSA in Surabaya from you?
@dikyarga Please add the the plan for Udinus yah. 

And btw, who is in charge for Binus?

**Comment by RizRiyz** [comment]
@kelimuttu you can use database here: https://docs.google.com/spreadsheets/d/1SkQ0mXEba7wBtooDP5wpD3XhpO0CGhx0ASVahYIcrfI/edit?pref=2&pli=1#gid=569214410

**Comment by kelimuttu** [comment]
Please add this to the campus list : 
- Unhas Makassar
- Universitas Islam Negeri Alauddin Makassar(UIN) 
- Universitas Negeri Makassar (UNM)

**Comment by RizRiyz** [comment]
@kelimuttu done.

**Comment by dikyarga** [comment]
> Benchmarks:
> End of May: Recruite 2 more active FSA from Surabaya
> End of May: 100+ firefox installation in ITS

I think this is make a sense, so in Udinus i will use this benchmarks too.
