### ISSUE TITLE
Mozilla Kisumu - LakeHub - Maseno University

### ISSUE THREAD

**Issue by chanditome** [mozilla/participation-leaders-accountability#62]
We already have an IoT initiative with Maseno University. It would be interesting to have the community plug into these activities. 

@lakehub has another Africa-wide initiative with SwahiliBox and Chimera IoT. I will be able to provide details later.

**Comment by AI-DennisNdegwa** [comment]
@chanditome add me as part of your initiative to help out wherever I can.
